version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/
hooks:
  ApplicationStop:
    - location: scripts/stoptomcat.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/starttomcat.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/monitortomcat.sh
      timeout: 3600
      runas: root
